refactor: useFetch 분리 / result page 결과값 수정
tooooo1/dust-rating pull request #11
Opened 2023-03-29 10:38 UTC by jaekwanAHN

1. 작업내용
- Result Page에 함께 있던 useFetch 함수를 다시 분리했습니다.
- Choice 화면에서 선택한 도시와 상관없이 Result 화면 상단에 표기되는 값이 일정했었습니다. 이제는 선택한 도시에 대한 정보가 표기됩니다. 
![image](https://user-images.githubusercontent.com/12118892/228505087-20511f0a-a0f1-4eb2-b855-ba2754dcce3a.png)
이전에는 어느 도시를 선택하든 통신결과 0번 째 인덱스에 해당하는 정보(도시 이름 제외)가 표기되었습니다.
- Progress 컴포넌트의 계산 방법을 수정했습니다. 미세먼지 수치가 100을 넘어가는 경우 Progress bar가 화면 밖으로 나가는 현상이 있었습니다. 기상청 통계 결과 역대 가장 심했던 서울의 미세먼지 농도는 1060㎍/㎥ 이상 이었습니다. 이는 역대 가장 높은 수치 였으므로 특별한 경우가 아니라면 1000㎍/㎥ 가 넘는 경우는 자주 발생하지 않을것으로 사료됩니다.
이에 따라 Progress bar의 계산식을 1/1000 으로 계산하도록 수정했습니다. 
![image](https://user-images.githubusercontent.com/12118892/228505902-45308ac7-4e61-44e3-85ca-76cb1405ac21.png)

2. 의견 필요
- 데이터를 다시 패칭하여 useFetch의 data State를 갱신하는 reFetch 함수를 useFetch안에 만들고 싶었습니다. 그리고 ```return {data , refetch }``` 와 같은 모습으로 만드려했습니다 만, 받는 쪽에서 type 문제를 해결하지 못하여서 우선 제외하고 PR을 날립니다. promiseAll 의 사용도 처음이라 어떤 방식으로 구현해야 할지 의견 주시면 감사하겠습니다. 
- 서비스 제목이 '"랭킹"먼지' 이므로 미세 먼지 농도 순위와 맞게 result page가 보여져야 한다고 생각됩니다. '미세먼지' + '초미세먼지' 값 등 다양한 sort 기준이 있을 것 같은데 어떤 기준이 적절할까요?

3. 추후 변경 
- 현재 각 지역에 대한 미세먼지 값은 각 '도'에 속한 지역중 4번 인덱스에 해당하는 값으로 보여집니다. 이를 계산하는 방식으로 각 '도'에 해당하는 더 작은 지역들의 미세먼지 평균값을 보여주는 것이 더 바람직하다고 생각되나 수정사항이 너무 많아지므로 현 PR 에서는 제외하였습니다.

2023-03-29 11:05 UTC, dmswl98 reviewed
pr 작성 정말 자세히 작성해주셔서 감탄하고 갑니다!!!! 수고하셨서용

2023-03-29 11:05 UTC, dmswl98 commented on src/hooks/useFetch.ts
> +  const [data, setData] = useState<dustDataType | []>([]);
변수와 타입이 구분되도록 타입명을 대문자로 시작하면 어떨까요?

2023-03-29 11:05 UTC, dmswl98 commented on src/pages/Result.tsx
> +  data.then((data) => setDustData(data));
setDustData를 수행하는 부분을 useEffect 내부에서 작성하는 것이 더 좋을 것 같아요!

2023-03-29 11:05 UTC, dmswl98 commented on src/pages/Result.tsx
> +  };
early return을 사용하면 더 좋을 것 같아요!
```js
if(!result) { return '' }
```

2023-03-29 11:11 UTC, tooooo1 requested changes
의견 필요
데이터를 다시 패칭하여 useFetch의 data State를 갱신하는 reFetch 함수를 useFetch안에 만들고 싶었습니다. 그리고 return {data , refetch } 와 같은 모습으로 만드려했습니다 만, 받는 쪽에서 type 문제를 해결하지 못하여서 우선 제외하고 PR을 날립니다. promiseAll 의 사용도 처음이라 어떤 방식으로 구현해야 할지 의견 주시면 감사하겠습니다.

- response에 type을 넣을 수 있어요 [axios](https://github.com/axios/axios/issues/1510)

서비스 제목이 '"랭킹"먼지' 이므로 미세 먼지 농도 순위와 맞게 result page가 보여져야 한다고 생각됩니다. '미세먼지' + '초미세먼지' 값 등 다양한 sort 기준이 있을 것 같은데 어떤 기준이 적절할까요?

- 오.... 동의합니다. 두 개를 합쳐서 랭킹을 할지 둘 중 하나를 기준으로 할지 은지님과 의견 나누어보시면 좋겠네요!

고민하신 흔적이 코드에서 많이 느껴졌어요!! ㅋㅋ그래서 재관님 fork 주소까지 들어가서 코드를 직접 보면서 리뷰 남겼습니다-! 빠샤빠샤~~

2023-03-29 11:11 UTC, tooooo1 commented on src/hooks/useFetch.ts
> +      return res;
음 여기서 return은 어떤 의미를 가질까요?

2023-03-29 11:11 UTC, tooooo1 commented on src/pages/Result.tsx
> +  data.then((data) => setDustData(data));
`useFetch`에서 data를 promise로 받고 then을 하는 것이 아닌 바로 data로 받아올 수 있는 방법은 없을까요?

2023-03-29 11:11 UTC, tooooo1 commented on src/pages/Result.tsx
> +  };
```suggestion
    if(result) return;
    
    if (kindOfdust === 'DustState') {
      return (
        (parseInt(result?.items[4]?.pm10Grade) +
          parseInt(result?.items[4]?.pm25Grade)) /
        2
      ).toString();
    } else if (kindOfdust === 'first') {
      return result?.items[4]?.pm10Value;
    } else if (kindOfdust === 'last') {
      return result?.items[4]?.pm25Value;
    } else return '';
  };
```

이런식은 어떤가요? 더 나아가서

```suggestion
    if(result) return;
    
    switch (kindOfDust) {
      case 'DustState':
        return (
          (parseInt(result.items[4].pm10Grade) + parseInt(result.items[4].pm25Grade)) / 2
        ).toString();
      case 'first':
        return result.items[4].pm10Value;
      case 'last':
        return result.items[4].pm25Value;
      default:
        return '';
    }
```

이렇게! 그리고 `first`, `last`보다 미세먼지, 초미세먼지임을 나타내주는 변수명이 더 좋을 것 같아요. 마지막으로 default로  `return ''`이 아닌 미세먼지나 초미세먼지 등을 default로 `return`해주는 게 더 바람직할 것 같기도해요.


정말정말 마지막으로 `findChoiceCity`이 함수명인데 이 함수 안에서 City도 찾고 미세먼지까지 찾아주는데 더 관심사를 분리할 수 있을 것 같아요. 먼가 짧은 코드 줄에서 5개정도 리뷰를 남겼는데 재관님이라면 멋지게 반영해주실 것 같아요!

2023-03-29 11:11 UTC, tooooo1 commented on src/pages/Result.tsx
> +        <Progress id="last" state={findChoiceCity('last')}>
`first`, 'last`는 위 리뷰에서 남겼어요-!

2023-03-29 11:20 UTC, dmswl98 commented on src/pages/Result.tsx
> +  data.then((data) => setDustData(data));
그리고 dustData값은 이후에 변경되지 않으니까 data값을 dustData '상태' 값으로 관리하지 않아도 될 것 같아요!!! 🧐

2023-03-30 11:11 UTC, jaekwanAHN commented on src/pages/Result.tsx
> +  data.then((data) => setDustData(data));
setDustData는 useEffect 내부로 이동시킬게요!

dustData에 관해서는 조금 더 이야기를 나누고 싶은 부분이있어요.
현재는 Result page에서 [ 미세먼지 | 초미세먼지] 수치와 상관없이 cityGroup 배열의 순서에 따라서 결과가 나열돼요.
그런데 서비스 이름에 '랭킹' 이 들어가는 만큼 수치에 따라서 정렬이 되면 좋겠다고 생각했어요. 
이때 사용자가 [ 미세먼지 | 초미세먼지] 를 선택할 수 있는 영역을 추가하고 이에 따라서 dustData를 정렬해서 보여주려면 '상태' 값으로 관리하는게 좋을 것 같아요. 

혹시나 다른 의견이 있으시다면 말씀해주세요~!

2023-03-30 13:25 UTC, jaekwanAHN commented on src/pages/Result.tsx
> +  };
흠... 함수를 분리하긴 했는데 제가 원하는 대로 분리되진 않았어요.
findChoiceCity 함수와 calculateFineDust 함수로 분리 되어있긴 하지만 결국엔 findChoiceCity 함수에서 calculateFineDust 함수를 불러서 사용하기 때문에 깔끔하게 분리되어 있지 않아요.
calculateFineDust 함수의 의존성을 제거하려는 과정에서 한가지 막힘이 있었어요. findChoiceCity에서 사용하는 dustData.find의 결과값 result를 전역으로 빼주고 calculateFineDust에서 result를 가져다가 쓰려고 했어요.
그러나 이렇게 할 경우 상단에 내가 선택한 도시의 미세먼지 progressBar가 정상적으로 출력되지 않더라구요. 
미세먼지에 대한 정보를 state로 빼서 result에 디팬던시를 둔 useEffect를 활용해 볼까 했지만 이 역시 정상적으로 출력도지 않았어요.

혹시 좋은 아이디어가 있을까요?

2023-03-30 13:28 UTC, jaekwanAHN commented on src/pages/Result.tsx
> +  };
default로 return 해주는 value 의 경우 숫자가 들어가게 되므로 '0' 이라는 값을 기본값으로 생각했는데 더 적절한 값이 있을지 궁금해요.

2023-03-31 03:34 UTC, dmswl98 commented on src/pages/Result.tsx
> +  data.then((data) => setDustData(data));
아하 `서비스 이름에 '랭킹' 이 들어가는 만큼 수치에 따라서 정렬이 되면 좋겠다고 생각했어요.` 이 부분은 저도 동의해요.
맞네요. 기존의 데이터 값의 순서를 몰랐었는데, 말씀 주신대로 cityGroup 배열의 순서에 따라서 결과가 나열되고 선택 영역에 따라 정렬해서 보여주려면 상태로 관리해도 좋을 것 같아요! 👍👍👍

2023-03-31 05:09 UTC, tooooo1 requested changes

2023-03-31 05:09 UTC, tooooo1 commented on src/type/index.ts
> +export type DustDataType = {
```suggestion
export type DustData = {
```

타입이 안 적혀도 될 것 같아요

2023-03-31 05:09 UTC, tooooo1 commented on src/pages/Result.tsx
> +    result: DustDataType;
```suggestion
    result: DustData;
```

2023-03-31 05:09 UTC, tooooo1 commented on src/pages/Result.tsx
> +import { DustDataType } from '@/type';
```suggestion
import { type DustData } from '@/type';
```

2023-03-31 05:10 UTC, tooooo1 commented on src/pages/Result.tsx
> +  };
지금방법도 나쁘지않다고 생각해요. 이전보다 훨씬 좋아졌어요 ㅎㅎ 그리고 0도 지금은 괜찮은 것 같긴해요

2023-03-31 09:41 UTC, jaekwanAHN commented on src/type/index.ts
> +export type DustDataType = {
충일님은 타입을 안적는걸 선호하시는군요!
가끔 변수명이랑 타입명이랑 겹치는 경우가 있어서 Type을 붙이곤 했었는데 안적는 방향도 생각해 봐야겠네요!

2023-03-31 09:44 UTC, jaekwanAHN commented on src/pages/Result.tsx
> +import { DustDataType } from '@/type';
type을 import 할때 type을 앞에 붙여줘야 하나요?

2023-03-31 22:15 UTC, tooooo1 approved these changes

2023-03-31 22:15 UTC, merged