feat: DustForecast 페이지 쿼리 스트링 적용
tooooo1/dust-rating pull request #126
Opened 2023-05-18 15:22 UTC by dmswl98

## 📌 이슈번호 

- close #125 

## 👩‍💻 요구 사항 
- DustForecast 페이지 쿼리 스트링 적용
- DustForecast 페이지 에러 바운더리 적용

## 🎨 구현 스크린샷 

https://github.com/tooooo1/dust-rating/assets/76807107/8a37c7e1-ca76-4d65-95dd-3119b793b425

## ✅ PR 포인트 
- 쿼리 스트링 값인 sido, city 값을 변경해 새로고침이 되어도 정상적인 데이터가 나오려면 api 호출이 불가피하다고 느껴 해당 페이지에서 api 호출 하도록 했어요.
- 유저가 올바르지 않은 지역을 검색한 경우를 대비해 errorBoundary를 적용해 fallback UI를 보이도록 했어요.

## 질문 
- errorBoundary 컴포넌트에 prop을 따로 넘길 수 없어 fallback UI 스타일이 이상해요.

2023-05-18 17:06 UTC, tooooo1 requested changes
### 질문
errorBoundary 컴포넌트에 prop을 따로 넘길 수 없어 fallback UI 스타일이 이상해요.
### 답변
스타일은 잘모르겠지만, 다시 시도라든지, 홈으로 이동이라는 버튼이 추가적으로 있으면 사용자 경험이 더 좋아질 것 같아요

2023-05-18 17:06 UTC, tooooo1 commented on src/components/Ranking/CityRankList.tsx
>          cityDustInfos.map((city, cityIndex) => (
```suggestion
        cityDustInfos?.map((city, cityIndex) => (
```

옵셔널을 활용한 코드가 더 깔끔해보여요

2023-05-19 03:21 UTC, tooooo1 requested changes

2023-05-19 03:21 UTC, tooooo1 commented on src/pages/DustForecast.tsx
> +    );
suspense를 이용해서 처리하면 어떨까요?

2023-05-19 04:41 UTC, jaekwanAHN commented on src/components/common/Fallback/ErrorFallback.tsx
> +    <Center isCenter={isCenter}>
chakra의 center를 사용할 수 도 있을까요?

2023-05-19 04:41 UTC, jaekwanAHN commented on src/pages/DustForecast.tsx
> +const INIT_SEARCHED_CITY = '강남구';
choice 페이지 에서도 기본 SIDO 값을 사용하더라구요.
constants 폴더로 뺴서 사용해도 좋을거같아요!

2023-05-19 06:54 UTC, tooooo1 approved these changes

2023-05-19 06:55 UTC, merged