feat: 도시 변경 select 스타일 수정
tooooo1/dust-rating pull request #153
Opened 2023-05-23 18:50 UTC by dmswl98

## 📌 이슈번호 

- close #151 

## 👩‍💻 요구 사항 
- 도시 변경 select 스타일 수정
- CityRanking 페이지 내 '지역별 미세 먼지 농도 순위' 배경색 변경
- eslint extends에 typescript-eslint 추가

## 🎨 구현 스크린샷 
![image](https://github.com/tooooo1/dust-rating/assets/76807107/56f8ed82-25b3-4174-bda3-d8b5d1fa840b)

https://github.com/tooooo1/dust-rating/assets/76807107/73829374-931a-46fa-80c7-a4a576892071

## ✅ PR 포인트 
- 아래처럼 버튼을 오른쪽에 두고 select의 dropdown 부분의 위치를 버튼과 맟추려고 했는데 위치를 따로 커스텀할 수 없어서 버튼을 왼쪽에 두었어요.

![image](https://github.com/tooooo1/dust-rating/assets/76807107/b5b2c6bb-ce24-40e9-b635-72b9e2797950)

## 질문

2023-05-23 20:44 UTC, jaekwanAHN requested changes
드롭 다운 보기 좋네용!
드롭 다운 위치는 좌표값을 음수로 해도 안되나보군요...
저도 고민해보겠습니다.

2023-05-23 20:44 UTC, jaekwanAHN commented on src/components/common/Select.tsx
> +        }}
DustChart에서도 동일한 내용의 속성들이 사용되는것 같아요!
상수로 처리할 수 있을까요?

2023-05-23 20:44 UTC, jaekwanAHN commented on src/pages/CityRanking.tsx
> +          bg={theme.colors[DUST_GRADE[sidoDustInfo?.fineDustGrade || 0]]}
0 대신 bgcolorGrade를 써보는건 어떠신가요?
DUST_GRADE[sidoDustInfo?.fineDustGrade 값이 없어도 'NONE'에 해당하는 색상이 아니라 이전에 보이던 색상을 유지할 수 있어요.

2023-05-23 20:44 UTC, jaekwanAHN commented on src/utils/constants/city.ts
>  ];
👍

2023-05-24 03:32 UTC, dmswl98 commented on src/components/common/Select.tsx
> +        }}
도전~!

2023-05-24 05:02 UTC, tooooo1 approved these changes

2023-05-24 16:42 UTC, merged