feat: SidoRanking, CityRanking 페이지 컴포넌트 리팩토링
tooooo1/dust-rating pull request #161
Opened 2023-05-25 10:10 UTC by dmswl98

## 📌 이슈번호 

- close #160

## 👩‍💻 요구 사항 
- SidoRanking, CityRanking 페이지 컴포넌트 리팩토링 

## 🎨 구현 스크린샷 

## ✅ PR 포인트 
- 각 SidoRanking, CityRanking 페이지의 정렬 상태 prop drilling이 너무 심해져서 정렬 상태를 contextAPI로 관리했어요.
- 중복되는 jsx를 컴포넌트로 따로 분리해 리팩토링했어요.
- SidoRankItem, CityRankItem -> RankItem

## 질문

2023-05-25 12:23 UTC, jaekwanAHN reviewed
어떤 컴포넌트는 Raking 이고 어떤 컴포넌트는 Rank 라는 네이밍을 사용하네요.
의도적으로 하신걸까요?!

2023-05-25 12:23 UTC, jaekwanAHN commented on src/store/sort.tsx
> +  setSortType: () => {},
린트 예외를 두지 않으면 린트 에러가 발생하나요?
```
interface test {
  testFunc: (e: MouseEvent<HTMLButtonElement>) => void;
}

const testOb: test = {
  testFunc: () => {},
};
```

를 제 환경에 입력했을 때 아무런 린트에러도 뜨지 않아서 여쭤봅니당

2023-05-25 14:45 UTC, jaekwanAHN commented on src/pages/CityRanking.tsx
>      );
sidoDustInfo를 fetch 하는 useQuery에서 suspense를 사용하면 해당 부분을 지우고 로딩중에 대한 처리를 AsyncBoundary에서 할 수 있지 않을까요?

2023-05-25 17:21 UTC, dmswl98 commented on src/store/sort.tsx
> +  setSortType: () => {},
엇 그럼 저는 왜 에러가 발생할까요오오ㅜㅜㅠㅜ

2023-05-25 17:24 UTC, dmswl98 commented on src/components/Ranking/CityRankList.tsx
> +import RankItem from './RankItem';
같은 폴더 내에 있는 경우에는 상대 경로를 사용했어요! 어떤 방식이 좋은 지는 저도 잘 몰라서 한 번 알아볼게요!

2023-05-25 17:25 UTC, dmswl98 commented
> 어떤 컴포넌트는 Raking 이고 어떤 컴포넌트는 Rank 라는 네이밍을 사용하네요. 의도적으로 하신걸까요?!

한 번 네이밍을 정리할 필요가 있는 것 같아요! 금요일날 정해봐요

2023-05-26 01:55 UTC, tooooo1 requested changes
달리시는군요!

2023-05-26 01:55 UTC, tooooo1 commented on src/components/Ranking/CityRankList.tsx
> +          location={`${ROUTE.DUST_FORECAST}?sido=${sido}&city=${city.cityName}`}
혹시 어떤 이유로 부모에서 이런식으로 내려주시는지 궁금해요

2023-05-26 01:55 UTC, tooooo1 commented on src/components/Ranking/RankItem.tsx
> +  };
```suggestion
  const handlePageNavigate = () => navigate(location);
```

개인적으로 저는 한줄이면 요걸 선호

2023-05-26 01:55 UTC, tooooo1 commented on src/App.tsx
> +      />
`Provider` 한번만 감싸는 방법은 없을까요?

2023-05-26 01:55 UTC, tooooo1 commented on src/components/Ranking/SidoRankList.tsx
> +        />
여기서도 어떤 배경에서 location을 위에서 넣어서 내려주는 이유랑 `rankTitle`를 추가로 설정하신 배경도 궁금합니다. `sido`를 `rankInfo`에서 받고있으니 props받은 데이터에서 `sido.sidoName`에 접근하면 되는데말이죠!

2023-05-26 07:27 UTC, dmswl98 commented on src/App.tsx
> +      />
city, sido 페이지 별로 sortType이 따로 관리되어야 되어야 하는데, 만약 루트에서 Provider를 한 번만 감싸게 되면
contextAPI에서 citySortType, sidoSortType이 관리되어야 해요.

그래서 저는 하나의 상태 sortType을 관리하고
아래 RankingContent.tsx 파일과 같이 CityRanking, SidoRanking 페이지 컴포넌트가 공통으로 사용하는 컴포넌트의 경우, 어떤 sortType을 사용할지 분기 처리 로직이 추가되지 않도록 구현했는데 어떤 방식이 괜찮은 건가요??????????
잘모르겟숴요..

```
// RankingContent.tsx
import { Flex, Text } from '@chakra-ui/react';
import { PropsWithChildren } from 'react';
import {
  AsyncBoundary,
  ErrorFallback,
  ListFallback,
} from '@/components/common';
import { useSort } from '@/store/sort';
import { KIND_OF_DUST } from '@/utils/constants';
import SelectTabList from './SelectTabList';

interface RankingContentProps {
  backgroundColor: string;
}

const RankingContent = ({
  children,
  backgroundColor,
}: PropsWithChildren<RankingContentProps>) => {
  const { sortType } = useSort();

  return (
    <Flex
      direction="column"
      justifyContent="center"
      alignItems="center"
      maxWidth="38rem"
      width="100%"
      margin="0 auto"
      borderRadius={20}
      bg="#ffffff"
      mb={20}
      px={{ base: '1rem', sm: 10, md: 16 }}
      py={10}
    >
      <Text
        as="p"
        fontSize={{ base: 12, sm: 14 }}
        margin="0 auto"
        px={8}
        py={3}
        borderRadius={25}
        color="#ffffff"
        bg={backgroundColor}
        transition="all 500ms ease-in-out"
      >
        지역별 {sortType} 농도 순위
      </Text>
      <SelectTabList selectTabList={KIND_OF_DUST} />
      <AsyncBoundary
        rejectFallback={
          <ErrorFallback errorMessage="지역별 미세먼지 정보를 불러오지 못했어요." />
        }
        pendingFallback={<ListFallback />}
      >
        {children}
      </AsyncBoundary>
    </Flex>
  );
};

export default RankingContent;
```

2023-05-26 07:35 UTC, dmswl98 commented on src/components/Ranking/SidoRankList.tsx
> +        />
CityRankList에서도 RankItem에게 prop으로 city를 내려주어 city.cityName으로 접근해야 하는데...
필드명이 달라서 그랬던 것 같아요. 그냥 name으로 통일하면 여러 prop을 내려주지 않아도 될 것 같네용

2023-05-26 08:40 UTC, jaekwanAHN reviewed
린트 예외 말고 아무것도 리턴 안하는 방법은 어떤가요?
```
() => {
    return;
   }
```

2023-05-26 09:19 UTC, tooooo1 commented on src/App.tsx
> +      />
일단 지금도 괜찮은 것 같습니다.

2023-05-26 09:19 UTC, tooooo1 approved these changes
원활한 작업을 위해 우선 머지 후 진행할게요..!

2023-05-26 09:23 UTC, tooooo1 commented
질문답변 드리면 interface SortContextState {
  sortType: SortType;
  setSortType: (e: MouseEvent<HTMLButtonElement>) => void;
}
이렇게 값과 타입명이 같아도 되려나요..?

우선 값과 타입명은 최대한 다르게 하는 것이 좋다고 생각합니다. 맨 앞에 대문자로 판단할 수도 있지만 혼란을 야기할 수도 있어서 개인적으로는요! 

💥💥💥
no-empty-function 린트 오류가 나는데 린트 설정에서 no-empty-function이 부분을 (전역적으로) 해제시켜야 할까요?
아니면 해당 부분만 해제하도록 하는 게 좋을까요?

해당 부분은 none이라는 함수를 만들어서 
`const none = () => {};`

여기에서만 린트 해제 주석을 달고 해당 함수를 return하면 되지않을까합니다~!

2023-05-26 09:23 UTC, merged