feat: DustMapPage 컴포넌트 ErrorBoundary 설정
tooooo1/dust-rating pull request #177
Opened 2023-06-29 12:25 UTC by dmswl98

## 📌 이슈번호 

- close #이슈번호

## 👩‍💻 요구 사항 
kakao map에 오류가 생겼을 때를 대비해 DustMapPage 컴포넌트에 ErrorBoundary 설정

## 🎨 구현 스크린샷 
![image](https://github.com/tooooo1/dust-rating/assets/76807107/a7cdee2e-dae7-4adf-ad16-d687254f750a)

## ✅ PR 포인트 
- dustmap 페이지에서는 지도 전체를 덮는 에러 fallback UI를 구현하기 위해 기존의 ErrorFallback 컴포넌트에서 size prop을 받도록 수정했어요.
- 에러 메시지 상수화 진행 + 에러 메시지 타입 좁히기

## 질문 
거의 모든 페이지 컴포넌트의 에러 바운더리가 라우터에서 설정되어 있어 한 번에 확인하기에는 편하지만 조금 지저분하다는 느낌... 어떻게 추상화할 수 있을까요...?

2023-07-01 13:31 UTC, tooooo1 requested changes
AsyncBoundary을 각각 거는 것이 과연 좋은 건지 먼저 고민하면 좋을 것 같아요.

ErrorBoundary와 Suspense를 결합한 형태인데 사실 ErrorBoundary만 컨트롤하고 있지는 않은지 추가적으로 더 어떤걸 고려할 수 있을지 등? 

errormessage 너무 좋군용 ㅋㅋ👍

2023-07-01 13:31 UTC, tooooo1 commented on src/components/common/ErrorFallback.tsx
> +  errorMessage: (typeof ERROR_MESSAGE)[keyof typeof ERROR_MESSAGE];
👍

2023-07-01 13:31 UTC, tooooo1 commented on src/components/common/ErrorFallback.tsx
> +  };
밖에 있으면 혹시 다른 방식으로 동작되나요?

2023-07-01 13:31 UTC, tooooo1 commented on src/components/common/ErrorFallback.tsx
> +      {...(size === fallbackSize.FULL && fullStyleProps)}
혹시 스타일을 다른 방식으로 주입하는 것도 있을까요?

2023-07-03 15:53 UTC, dmswl98 commented on src/components/common/ErrorFallback.tsx
> +  };
오호.. 아뇨^_^

2023-07-03 15:59 UTC, dmswl98 commented on src/components/common/ErrorFallback.tsx
> +      {...(size === fallbackSize.FULL && fullStyleProps)}
어험 모르겠습니다. 각 속성마다 조건에 따라 값을 주입하는게 지저분할 것 같아서 `fullStyleProps` 객체 통째로 주입하도록 했어요.

2023-07-03 16:01 UTC, dmswl98 commented on src/components/Map/index.tsx
>        {!cityDustInfoList ? <Spinner zIndex={10} /> : ''}
이 부분은 빈 문자열 대신 `null`을 반환하는게 맞지 않을까? 하는 생각.

2023-07-04 04:12 UTC, jaekwanAHN commented on src/components/Map/index.tsx
>        {!cityDustInfoList ? <Spinner zIndex={10} /> : ''}
혹시 `null`을 반환하면 null 이라고 출력되진 않나요?

2023-07-04 07:21 UTC, dmswl98 commented on src/components/Map/index.tsx
>        {!cityDustInfoList ? <Spinner zIndex={10} /> : ''}
```suggestion
      {!cityDustInfoList && <Spinner zIndex={10} />}
```
빈 문자열보다 요렇게 아무것도 반환하지 않도록 수정하는게 좋을 것 같아요~!

2023-07-06 14:57 UTC, tooooo1 requested changes

2023-07-06 14:57 UTC, tooooo1 commented on src/components/common/CustomErrorBoundary.tsx
ErrorBoundary만 적용하고 싶은 경우를 위해 CustomErrorBoundary라는 컴포넌트로 분리했어요.
-> ErrorBoundary만 적용하고 싶은 경우인데 네이밍이 CustomErrorBoundary여야할까요? 그냥 ErrorBoundary여도 되지않을까요? 커스텀이 추가되어야하면 어떤게 커스텀 되었나요?

2023-07-07 05:40 UTC, jaekwanAHN commented on src/pages/DustForecast.tsx
> +import { ERROR_MESSAGE } from '@/utils/constants/message';
constants 폴더의 index에서 가져오는 값들과 1 뎁스 더 들어가서 가져오는 값들은 어떤 차이가 있나요?

2023-07-07 11:41 UTC, dmswl98 commented on src/components/common/CustomErrorBoundary.tsx
'react-error-boundary'의 `ErrorBoundary` 이름이 겹쳐서 커스텀을 붙인 거였어요..! 수정했습니다!

2023-07-07 11:41 UTC, dmswl98 commented on src/pages/DustForecast.tsx
> +import { ERROR_MESSAGE } from '@/utils/constants/message';
아앗... 수정했어요!

2023-07-08 03:59 UTC, tooooo1 approved these changes
좋아요

2023-07-08 04:00 UTC, merged