feat: 정렬 기준에 내림차순, 오름차순 추가
tooooo1/dust-rating pull request #178
Opened 2023-06-29 17:51 UTC by jaekwanAHN

## 📌 이슈번호 

- close #172 

## 👩‍💻 요구 사항 
- 정렬 기준에 오름차순, 내림차순이 추가 되었습니다.
- context의 sortType을 dustType으로 이름 변경 하였습니다. 그리고 새로운 sortType을 추가하였습니다. 이제 dustType이 어느 먼지로 정렬할지 나타내고 sortType이 오름,내림 차순 정렬을 의미합니다.
- 기존 store에 미세먼지, 초미세먼지 정보를 담아서 정렬하던 것을 활용하였습니다.
- conponents > Ranking > SelectTabList 컴포넌트에서 onClick 함수도 prop으로 받도록 수정하였습니다. 

## 🎨 구현 스크린샷 
[chrome-capture-2023-5-30.webm](https://github.com/tooooo1/dust-rating/assets/12118892/34b4ba62-c201-4478-bb7c-9baa24cc261b)

## ✅ PR 포인트 

## 질문

2023-06-29 23:52 UTC, tooooo1 reviewed
`SelectTabList`를 재사용하셨네요! 그런데 UX/UI적으로 아쉬운거같아요.
같은 컴포넌트를 그냥 사용하셔서 미세먼지, 초미세먼지와 오름차순, 내림차순이 동등한 레벨인 것 처럼 보여요.

미세먼지, 초미세먼지가 더 high level이어야하고 sort는 부수적이어야할거같다고 생각이 드는데 어떻게 생각하시나요?

2023-07-08 07:53 UTC, jaekwanAHN commented
@tooooo1 
우선 리뷰 반영이 늦어서 죄송합니다.

> SelectTabList를 재사용하셨네요! 그런데 UX/UI적으로 아쉬운거같아요.
같은 컴포넌트를 그냥 사용하셔서 미세먼지, 초미세먼지와 오름차순, 내림차순이 동등한 레벨인 것 처럼 보여요.
미세먼지, 초미세먼지가 더 high level이어야하고 sort는 부수적이어야할거같다고 생각이 드는데 어떻게 생각하시나요?

맞아요. 재사용에만 초점을 맞추다보니 생각하지 못했던 부분이었어요. 
그래서 `SelectTabList` 에서 옵셔널 하게 받을 수 있도록 수정해 보았어요. 동등한 2개의 컴포넌트가 아니라 1개의 컴포넌트에서 관리 할 수 있으니까 말씀 해주신 문제점이 해결되었다고 생각할 수 있을까요?

그리고 `SelectTabList` 에서 정렬할것, 옵션이 둘 다 `<TabList>` 로 만들어져요. 그래서 25~45줄에 같은 코드가 2번 반복되는 모양새인데 해당 부분도 따로 컴포넌트로 만들어야 하나 고민되네요.

2023-07-13 01:42 UTC, tooooo1 approved these changes
코드적인 리뷰말고 사용자 관점에서 리뷰드렸었던거였어요 ㅎㅎ

2023-07-13 01:43 UTC, tooooo1 requested changes
애러 해결해주시고 다시 리뷰요청 부탁드려요

2023-07-13 01:43 UTC, dmswl98 commented
@jaekwanAHN 엇 오름차순이랑 내림차순이 위 미세먼지 탭이랑 UI가 비슷해서 헷갈릴 것 같은데 아이콘으로 변경하는 건 어떠신가오

2023-07-13 11:30 UTC, jaekwanAHN commented
@dmswl98 저도 처음엔 그렇게 생각했었는데 사용해보신 분들 중에서 '이거 정렬 순서가 뭐에요?' 라고 하신분이 계셔서 '직관적으로 알기엔 부족한가?' 라는 생각에 추가 하기로 했었습니다. '오름차순, 내림차순' UI의 모양을 좀 바꿔서 적용하면 괜찮아질것 같네요. 충일님 의견처럼 하위 레벨에 속하는 버튼이라는 느낌이 들도록요! 은지님 의견처럼 아이콘으로 하는것도 좋을거 같아요!

2023-07-30 10:52 UTC, tooooo1 commented
PR이 올라온지 좀 되어서, 현재 진행중인가요? 아니라면 close하려고 합니다.

2023-08-03 15:10 UTC, jaekwanAHN commented
신경을 못쓰고 있었네요. 
우선 draft로 바꾸어 놨는데 close 했다가 추후에 다시 올릴까요?

2023-08-05 01:36 UTC, tooooo1 commented
👍🔥

2023-08-05 04:41 UTC, closed without merging