chore: 패키지 버전 업데이트
tooooo1/dust-rating pull request #2
Opened 2023-03-26 14:15 UTC by dmswl98

## 📖 작업 내용
- [x] 기존 패키지를 최신 버전으로 업데이트

![image](https://user-images.githubusercontent.com/76807107/227781607-143f1e81-e4dd-4f2a-927f-677829429ff7.png)

2023-03-26 22:21 UTC, tooooo1 requested changes
오 vite+ ts.... 너무 좋아하는 조합이에용ㅋㅋㅋㅋㅋ

2023-03-26 22:21 UTC, tooooo1 commented on .env.example
> +VITE_OPEN_URL =
EOL에 대해 고려해주세요!

2023-03-26 22:21 UTC, tooooo1 commented on index.html
> +    <title>랭킹먼지</title>
우리 사용하지 않는 주석은 제거하는건 어떨까요?

2023-03-26 22:21 UTC, tooooo1 commented on src/App.tsx
> +
여기도 사용하지않는다면 주석을 지우는게 더 좋을것같아요!

2023-03-26 22:21 UTC, tooooo1 commented on package.json
> +    "styled-reset": "^4.4.5"
이건 어떤 역할을 할까요? 우리 프로젝트에 꼭 필요할까요?

2023-03-26 22:21 UTC, tooooo1 commented on src/main.tsx
> +ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
as 키워드를 사용하지 않아도 될 수 있을 것 같아요 
+ 추가적으로 `as HTMLElement`는 왜 필요할까요?

2023-03-26 22:25 UTC, tooooo1 commented on .env.example
> +VITE_OPEN_URL =
![image](https://user-images.githubusercontent.com/77133565/227808453-b434340b-d53b-4a66-93c2-5f70b52d3b93.png)

왜 깃허브에서 저 아이콘을 나타낼까요?

2023-03-26 22:25 UTC, tooooo1 commented on package.json
> +    "styled-reset": "^4.4.5"
`styled-reset`

2023-03-27 02:57 UTC, dmswl98 commented on package.json
> +    "styled-reset": "^4.4.5"
내장 스타일을 모두 초기화하는 역할을 합니다. 꼭 필요한 건 아니지만 만약 삭제한다면 이미 작업한 스타일에 영향을 줄 수도 있을 것 같아요!

2023-03-27 03:04 UTC, dmswl98 commented on .env.example
> +VITE_OPEN_URL =
파일마다 개행을 수행해야 각 파일을 구분하는데에 도움이 되기 때문이죠.... 그러고 보니 prettier, eslint에 endOfLine가 설정이 안되어 있네요! 근데 endOfLine를 설정했는데도 env 파일에서는 왜 적용이 안될까요...? 👀

2023-03-27 03:19 UTC, dmswl98 commented on src/main.tsx
> +ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
index.html에 있는 root의 요소가 null일 수도 있기 때문에 타입스크립트에게 as 단언을 이용해 HTMLElement임을 다시 한 번 알려주는 걸로 알고 있어요! as 단언을 최대한 지양해야 하는 건 알았는데 이 부분까지 지양할 생각은 못했네요...!

2023-03-27 03:23 UTC, dmswl98 commented on src/App.tsx
> +
오 지워도 되는 건가요...?!?! 2222

2023-03-27 03:23 UTC, dmswl98 commented on index.html
> +    <title>랭킹먼지</title>
오 지워도 되는 건가요...?!?!

2023-03-27 05:03 UTC, tooooo1 commented on .env.example
> +VITE_OPEN_URL =
env는 일반적인 소스파일이 아니라 적용이 안 되어요. 적용을 하려면 추가적으로 `overrides`를 해야하는데 제 생각에는 과하다고 생각들어서 신경써서 EOL을 해주시는 방법이 더 좋다고 생각해용 ㅋㅋ 반영해주신것 확인했습니다!!

2023-03-27 05:05 UTC, tooooo1 commented on index.html
> +    <title>랭킹먼지</title>
앞으로 은지님이 판단하시고 지워주시면 돼요! 저는 지워야한다고 생각해요.
cra에서 vite로 마이그레이션을 진행하면서 이제 더이상 `%PUBLIC_URL%` 경로가 적용이 안 될텐데요. 
그러면 의미있는 코드일까요? 의미가 없다면 존재할 필요가 있을지!!

2023-03-27 05:06 UTC, tooooo1 commented on src/App.tsx
> +
주석은 정말 의미가 있지않다면 지우는편을 개인적으로 선호해요 저는!

2023-03-27 05:08 UTC, tooooo1 commented on src/main.tsx
> +ReactDOM.createRoot(document.getElementById('root') as HTMLElement).render(
`ReactDOM.createRoot(document.getElementById('root')!)`
오 정확해요!! 그렇지만 이렇게 해도 돼요 ㅎㅎ

2023-03-27 14:52 UTC, tooooo1 requested changes
리뷰를 잘 반영해주셨네요! 그런데 커밋메세지 중에
[refactor: pr 리뷰 반영](https://github.com/tooooo1/dust-rating/pull/2/commits/e7a49157e49c6e7fc1226f973467b888aa3b6154)가 있었는데요.

메세지만 보았을 때 어떤 리뷰를 반영했는지 적혀있지 않아서 확인하는데 살짝 어려움을 느꼈어요. 너무 추상화하기보다 자세히 적어주시면 동료개발자분들이 확인할 때 더 좋을 것 같아요!ㅋㅋ

바로 merge 하기에는 아직 개선해야하는 부분이 몇개 보여서 코멘트 조금 남겼어요! 간단한거라서 확인해주세요!

2023-03-27 14:52 UTC, tooooo1 commented on index.html
> +
```suggestion
```

2023-03-27 15:29 UTC, dmswl98 commented on src/App.tsx
> +export default App;
파일 체인지가 너무 많아져서 브랜치 파서 하려고 했는데...! 일단 기존처럼 접근 가능하도록 고쳐놓았습니다.

2023-03-27 15:30 UTC, dmswl98 commented on .env.example
> +VITE_OPEN_URL =
변경 완료!

2023-03-27 15:35 UTC, tooooo1 approved these changes

2023-03-27 15:35 UTC, tooooo1 commented on src/components/Logo.tsx
> +import { Outlet } from 'react-router-dom';
와 처음보네요 배워갑니다!

2023-03-27 15:35 UTC, tooooo1 commented on src/pages/Result.tsx
> -import React, { useState } from 'react';
👍

2023-03-27 15:35 UTC, merged