feat: 지역 상세 날씨 페이지 추가.
tooooo1/dust-rating pull request #20
Opened 2023-03-31 09:01 UTC by jaekwanAHN

작업 시간이 너무 길어지고 있는것같아 중간 PR을 한 번 올리도록 하겠습니다.
디자인은 완성된 것이 아니며, 내용 또한 추가될 것입니다.
![image](https://user-images.githubusercontent.com/12118892/229073051-0da78aa0-fd22-46ba-a2de-4a582ce3dc19.png)

1. 작업내용
- Result Page에서 sido 클릭후 상세지역을 클릭하면 LocalDetail Page로 이동합니다.
- LocalDetail Page로 이동할 때 해당 지역의 dataTime, stationName,  pm10Value, pm25Value, pm10Grade, pm25Grade 정보를 props 로 넘겨줍니다. 이를 통해 해당 지역의 정보를 나타냅니다.
- 상단에 선택한 지역의 이름, 갱신 시간이 표기됩니다. (현재는 1시간 단위로 갱신됩니다)
![image](https://user-images.githubusercontent.com/12118892/229072746-2bdf6bb3-2be4-410e-ae81-dc26debbb017.png)

- 해당 지역의 미세먼지, 초미세먼지 수치를 나타낼 때 수치에 따라 글자와 숫자의 색상이 변화합니다.
![image](https://user-images.githubusercontent.com/12118892/229072443-42f00cdb-9775-46ce-97cd-c01e6f2283e7.png)
초/미세먼지 수치는 한국통계청 자료를 기반으로 하였으나 해당 자료가 17년도 자료였으므로 현재 기준이 변화하였을 수 있습니다.
- 미세먼지와 관련한 일기 예보가 출력됩니다. 
![image](https://user-images.githubusercontent.com/12118892/229072990-6f4b44d1-8193-47af-a060-868ee0a9d10b.png)

- 가장 아래쪽에는 당일, 명일의 미세먼지, 초미세먼지 기상예측 사진이 출력됩니다.
![image](https://user-images.githubusercontent.com/12118892/229072895-9d94e497-f951-4dc3-8465-ebb6abe6f28a.png)

2. 문제점
- 내 위치의 기상 예보를 알기 위해서는 위/경도 가 아닌 x,y grid 좌표가 필요합니다.

- 현재 온도, 습도의 경우 사용자의 현재위치를 기반으로 출력됩니다. 사용자가 선택한 지역의 데이터를 가져오고 싶었으나 위/경도 -> x,y 좌표 환산 함수(Translate.ts)에서 반복적으로 NaN이 출력되고 있습니다. navigator.geolocation.getCurrentPosition를 사용하여 '현재 내위치'를 input으로 했을 땐 정상값이 출력됩니다. 입력값은 항상 number형 위/경도 인데 어떤 차이가 있는지 아직 모르겠습니다.
- 내 위치 기반으로 일기 예보를 요청할 때API 서버에 데이터가 없는 시간대가 존재합니다. 추후에 API 문서를 다시 읽어보도록 하겠습니다.
- LocalDetail.tsx의 fetchLocation함수의 경우 선택한 상세장소에 대한 x,y grid 좌표를 받아오기 위해서 작성했으나 Translate.ts 함수가 정상 작동한다면 삭제하기 위해서 임시로 주석처리해두었습니다.
- LocalDetail.tsx에서 지금 날자, 시간을 구하는 과정이 깔끔하지 않습니다. 이에 대한 피드백이 있다면 감사합니다.

3. 추후
- LocalDetail.tsx파일의 길이가 많이 길어진 상태입니다. 모든 기능이 정상적으로 동작한다면 API fetch와 관련된 함수들 우선으로 하여 파일을 분리하도록 하겠습니다.
- DustState.tsx, FineDustState.tsx, UltraFineDustState.tsx의 기능이 비슷합니다. 추후에 한개의 파일로 합쳐서 관리하는 것이 좋을까요?

4. 의견필요
- 좌표 전환이 정상적으로 동작하지 않아 시간이 오래걸렸습니다. 아마 그래프를 추가한다면 이 이상 혹은 비슷한 시간이 소요될 것 같은데 그래프를 넣는 것이 좋을지, 아니면 다른 컨텐츠로 영역을 구상하는 것이 좋을지 궁금합니다~_~

2023-03-31 18:02 UTC, dmswl98 reviewed
재관님 정말 수고하셨습니당!!!

2023-03-31 18:02 UTC, dmswl98 commented on src/pages/LocalDetail.tsx
> +            })}
```suggestion
            {forecastImg.map((value) => <img key={value} width="30%" src={value} />)}
```
바로 리턴해도 좋을 것 같아용!

2023-03-31 18:02 UTC, dmswl98 commented on src/pages/LocalDetail.tsx
> +  font-family: 'Pretendard-Regular';
이 부분 모두 지워주시면 폰트가 제대로 적용될 거예요!

2023-03-31 18:02 UTC, dmswl98 commented on src/components/Translate.ts
> +var YO = 136; // 기1준점 Y좌표(GRID)
와우.... 대박

2023-04-01 09:24 UTC, tooooo1 requested changes
허허... 작업량이 상당하시네요. 리뷰해드리기전에 앞서 드리고싶은 말씀이 있어요.
`fast-xml-parser`는 필요없어요. 해당 API의 데이터 포맷이 `XML+JSON`이고 디폴트가 `XML`이라 변환 라이브러리를 설치하신 것 같은데 링크에 `json`으로 달라하면 바로 줍니다....! 확인해주시고 제거 부탁드려요!


좌표 전환이 정상적으로 동작하지 않아 시간이 오래걸렸습니다. 아마 그래프를 추가한다면 이 이상 혹은 비슷한 시간이 소요될 것 같은데 그래프를 넣는 것이 좋을지, 아니면 다른 컨텐츠로 영역을 구상하는 것이 좋을지 궁금합니다.
- 작업 시간이 고민이신 것 같아요. 경험이 쌓이다보면 어떤부분이 맞는지 알 수 있다고 생각하는데 지금은 학습목적이니 시간이 걸리는건 어쩔 수 없다고 생각해요. 시간이 안 걸리는 작업만 하면 옳은 판단일 수 있지만 성장한다고 말할 수 있을까요? 지금 어떤 목적으로 하고있는지 고민해주시고 판단하시면 좋을 것 같습니다 ㅎㅎ!

PR을 작게 작게 올리고 싶었는데 page를 담당해서 하다보니 여기서 올려도 되나? 라는 의문이 계속 들어요. 어떻게 PR을 해야 보는 사람도, 작업하는 입장에서도 깔끔할까요? 흠?
- 저는 보통 1, 2개의 기능을 추가할 때마다 PR을 올려요. 지금정도의 작업량으로 올려주시는 것도 나쁘지않다고 생각해요

2023-04-01 09:24 UTC, tooooo1 commented on src/components/Rank.tsx
> +
이건 필요한 스타일 변수선언일까요?

2023-04-01 09:24 UTC, tooooo1 commented on src/components/UltraFineDustState.tsx
> +import styled from 'styled-components';
어라 `styled-components`는 우리 프로젝트에서 사라지지않았나요? 이제보니 충돌이 엄청 발생하고 있네요! 최신화를 진행해주시고 다시 리뷰 요청을 보내주세요!

2023-04-01 16:59 UTC, jaekwanAHN commented on src/components/UltraFineDustState.tsx
> +import styled from 'styled-components';
이런! 제가 제거 하자고 해놓고 자연스럽게 ```styled-components```를 써버렸네요. 부끄럽습니다. :(

2023-04-02 09:41 UTC, tooooo1 requested changes
고생하셨어요! 리뷰 반영 잘봤어요.
추가적으로 20개가 좀 안 되는데 최대한 반영해주시면 감사드릴게요!

반영해주시고나면 이번 PR은 한번 더 핑퐁을 해야할 것 같아요...!

2023-04-02 09:41 UTC, tooooo1 commented on package.json
> +    "stylis": "^4.1.3"
필요한가요? 사용이 안 되고 있네요 ㅠㅠ

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Detail.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Detail.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Detail.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Detail.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Detail.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Progress.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Progress.tsx
> +
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Rank.tsx
>    const [click, setClick] = useState(true);
더 직관적인 변수을 주면 더 좋을 것 같아요!

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Rank.tsx
> +        dust: pm10Value,
미세먼지와 초미세먼지에 대해 약속을 하신걸로 알고있어요. 그런데 여기는 제가 아는 약속이랑 일치하지 않는 것 같은데 맞을까요? 맞다면 일치시키면 더 좋을 것 같아용

2023-04-02 09:41 UTC, tooooo1 commented on src/components/Translate.ts
이 파일..... 할 말이 많은데.. ㅠ 꼭 필요한가요? 필요하다면 더 깔끔한 코드는 없을까요? ㅜ

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  });
좋네요👍

그런데 은지님은 서울역?을 초기값으로 해주신 것 같은데 서로 상의하셔서 값 일치를 해주시면 더 좋을 것 같아요. 파편화가 시작되기 전에!

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  // const parser = new XMLParser();
?! 꼭 필요한 주석인가요? (질문)
```suggestion
```

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +    const longitude = coords.longitude; // 경도
이거는 변수명에서 충분히 추론 가능할 것 같아서 주석 필요 없다고 생각해요!

```suggestion
    const latitude = coords.latitude;
    const longitude = coords.longitude;
```

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +    const TT = Array.from(Object.values<string>(imgSets));
TT는 어떤건가요?

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  /* background-color: white; */
전체적으로 이 파일에서 주석이 많네요 ㅜ

2023-04-02 09:41 UTC, tooooo1 commented on src/pages/Result.tsx
불필요한 공백은 지워주세요!

2023-04-02 10:07 UTC, jaekwanAHN commented on src/pages/LocalDetail.tsx
> +  // const parser = new XMLParser();
'선택한 지역 기준으로 온도,습도 받아오기'를 하려고 작성했던 함수인데 해당 함수에서 갱신한 위/경도 값으로 x,y 좌표 변환을 시도하면 정상적인 값이 반환되지 않고 NaN이 반환되어서 일단 주석처리 해두었습니다.

2023-04-02 10:11 UTC, jaekwanAHN commented on package.json
> +    "stylis": "^4.1.3"
Progress.tsx 에서 사용되고 있어요!
이전에 PR에서 type 패키지가 존재하지 않아서 ```// @ts-ignore``` 와 함께 사용한 부분입니다.

2023-04-02 10:33 UTC, tooooo1 commented on package.json
> +    "stylis": "^4.1.3"
`react-sweet-progress`는 말씀하신 `Progress.tsx`에서 사용되고 있는 것 확인했어요.
이번 PR에서 추가된 `stylis` 말씀드린거였습니당. 저 처음보는데 어떤건가요?

2023-04-02 10:33 UTC, tooooo1 commented on package.json
> +    "stylis": "^4.1.3"
`react-sweet-progress`는 말씀하신 `Progress.tsx`에서 사용되고 있는 것 확인했어요.
이번 PR에서 추가된 `stylis` 말씀드린거였는데 처음보고 사용이 안 되는 것 같아서요. 어떤건가요?

2023-04-02 11:16 UTC, tooooo1 requested changes

2023-04-02 11:16 UTC, tooooo1 commented on src/components/Detail.tsx
>    font-size: 2vh;
이 부분도 수정되면 좋을 것 같은데 어떻게 생각하시나요? 제가 이전에 높이에 따라 font-size가 변경되게 코드를 작성했는데 높이에 따라 변경되는건 좋지않다고 생각해요 ㅠㅠ

2023-04-02 11:16 UTC, tooooo1 commented on src/components/Dust/FineDustState.tsx
> +    );
```suggestion
   if (isNaN(fineDustState))
    return (
      <DustStateColor color="#666666">{fineDustState}측정중</DustStateColor>
    );
  if (fineDustState < 80)
    return <DustStateColor color="#1E64EE">{fineDustState}좋음</DustStateColor>;
  if (fineDustState < 150)
    return <DustStateColor color="#00D500">{fineDustState}보통</DustStateColor>;
  if (fineDustState < 300)
    return <DustStateColor color="#F95A20">{fineDustState}나쁨</DustStateColor>;
```

순서가 바뀌어야할것 같아요!  `isNaN`이 맨 위로!

근데 이부분 `<DustStateColor color={color}>{content}</DustStateColor>`이 반복되는데 리팩터링이 가능할 것같아요 ! ㅋㅋ 이건 나중에 여유되시거나 신경쓰이시면 진행해주시면 좋을 것 같습니다

2023-04-02 11:16 UTC, tooooo1 commented on src/components/Dust/UltraFineDustState.tsx
이 파일이 의미가 있을까요? `FineDustState랑 정확하게 코드가 일치해서... ㅠ 파일명도 살짝 아쉬운데 State가 꼭 들어가야할까요? react에서 state의 이미지가 너무 강해서요

2023-04-02 11:16 UTC, tooooo1 commented on src/components/Rank.tsx
>    const [click, setClick] = useState(true);
click 변수명은 아직 반영이 안 된 것 같네요

2023-04-02 11:16 UTC, tooooo1 commented on src/components/Rank.tsx
> +        dust: pm10Value,
여기도 반영이 누락된 것 같아요

2023-04-02 11:55 UTC, jaekwanAHN commented on package.json
> +    "stylis": "^4.1.3"
다른곳에서 stylis 모듈을 찾을 수 없다는 에러가 떠서 설치했었는데, 방금 uninstall 해보니까 그런 에러가 사라졌네요.

해당 내용과 관련해서 캡쳐해서 어딘가에 글을 남겼던거 같은데 어디에도 없네요.........

2023-04-02 11:58 UTC, jaekwanAHN commented on src/components/Detail.tsx
>    font-size: 2vh;
다른 부분에서도 font-size: vh ,vw 가 많이 쓰였어요. 
미디어 쿼리가 쓰인 부분에서는 px 값이 쓰였는데 vh, vw 대신 rem 값을 사용 해보는 것이 좋을까요?

2023-04-02 13:18 UTC, tooooo1 requested changes
코드가 점점 더 예뻐지고 있는 게 체감되네요 ㅋㅋㅋ 
아직 머지하기에는 아쉬운 부분이 조금 더 보여서 ㅠㅠ 10개정도 더 리뷰 남겨드려요~!

2023-04-02 13:18 UTC, tooooo1 commented on .env.example
> +VITE_KAKAO_API_KEY =
```suggestion
VITE_API_KEY = 
VITE_OPEN_URL = 
VITE_WEATHER_API_KEY = 
VITE_KAKAO_API_KEY = 

```
불필요한 공백이 추가되었고 EOL이 적용 안 되어 있네요오--!
![image](https://user-images.githubusercontent.com/77133565/229354853-459eb97b-75ea-4132-9290-f8a35d1d48ed.png)

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Detail.tsx
파일명 개선이 필요할 것 같아요 `Detail`이란 어떤 `Detail`인지!!

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Detail.tsx
> +const Detail = ({
여기서도 어떤 `Detail`인지 더 명확하면 좋을 것 같습니다. 미세먼지랭킹에 관한 Detail일까요?

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Detail.tsx
> +          </DustWrapperFlex>
우와 이부분 완전 중복이네요? 저 없애고 싶어요 ㅋㅋ

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Detail.tsx
> +      <Top>
Top은 머지용? (제가 했지만ㅋㅋ)

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +  let result = 0;
와 완전 예뻐졌네요!!!!! 진짜 대박ㅋㅋ 마지막으로 우리 이 부분 한번 더 고민해볼까요?

저는 `let`을 사용하지 않는데 이거 없앨 수 있을 것 같아요 ㅋㅋ

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +  }
`avg`나 `finDust` 등을 상수화하면 더 멋지겠네요~!

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Rank.tsx
> +import { DetailType } from '@/type';
타입인데 끝에 Type이 필요한가요? 컨벤션인가요?

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Rank.tsx
> +    dataTime,
띄어쓰기의 규칙이 있나요? 
추가적으로 왜 한개는 `handle`이고 `Handle`일까요? 오타같네요

2023-04-02 13:18 UTC, tooooo1 commented on src/components/Rank.tsx
> +    <RatingWrapper onClick={HandleClickShowDetail}>
오타여도 여기서 발견할 수 있었을 것 같은데 아쉽긴하네요 ㅠㅠ

2023-04-02 13:25 UTC, tooooo1 commented on src/components/Detail.tsx
>    font-size: 2vh;
네 `rem`이 훠어얼씬 좋다고 생각해요 ㅋㅋ

2023-04-02 13:40 UTC, dmswl98 commented on src/pages/LocalDetail.tsx
> +  });
오호 그럼 제가 이 부분  `const DEFAULT_LOCATION = { latitude: 37.5665, longitude: 126.978 };` 상수화 해둘게요!

2023-04-02 13:42 UTC, dmswl98 commented on src/components/Detail.tsx
>    font-size: 2vh;
왜 저한테는 그런 피드백을 주시지 않으셨나요오.....

2023-04-02 13:44 UTC, tooooo1 commented on src/components/Detail.tsx
>    font-size: 2vh;
@dmswl98 
엇 놓쳤네요 ㅠㅠ 은지님도 반영부탁드려요!

2023-04-02 14:33 UTC, jaekwanAHN commented on src/components/Rank.tsx
> +import { DetailType } from '@/type';
컴포넌트 이름이랑 겹치는 경우가 있어서 헷깔리지 않기위해서 TYPE을 붙여줬어요.
흠...네이밍을 변경하는게 나을지 고민되네요.

2023-04-02 14:41 UTC, tooooo1 commented on src/components/Rank.tsx
> +import { DetailType } from '@/type';
@jaekwanAHN 
정답은 없을 것 같은데 통일성이 있으면 좋을 것 같아요. 
@dmswl98 은지님이랑 타입명에 대해 규칙을 통일하는 게 좋은 방법일 것 같아요 ㅎㅎ

2023-04-02 16:24 UTC, jaekwanAHN commented on src/components/Rank.tsx
> +    dataTime,
따로 띄어쓰기 규칙이 있는건 아니고 비슷해 보이는 것들끼리 묶거나 너무 모여있으면 임의로 적용 했었어요.
뭔가 일관성 있게 적용하는 방법을 생각해봐야겠네요.

2023-04-02 17:21 UTC, tooooo1 requested changes
리뷰할게 점점 더 많아지네요...! 14개 리뷰 우선 먼저 남겨요...!

2023-04-02 17:21 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +const KIND_OF_DUST_ULTRAFINEDUST = 'ultraFineDust';
같은 관심사인데 하나로 묶는건 어떤가요? 다음과같이

```suggestion
const DUST_KIND = {
  AVG: 'avg',
  FINE_DUST: 'fineDust',
  ULTRA_FINE_DUST: 'ultraFineDust',
};
```

2023-04-02 17:21 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +  };
`+dustDensity`가 반복적으로 사용되는데 차라리 맨 위에서 바꾸는건 어떨까요?

`const 나는_숫자 = +dustDensity;`

2023-04-02 17:21 UTC, tooooo1 commented on src/components/Rank.tsx
> +      },
```suggestion
      state: {
        stationName,
        fineDust: pm10Value,
        ultraDust: pm25Value,
        dustState,
        dataTime,
      },
```

자바스크립트의 Object initializer 개념을 활용하면 더 좋을 것 같아요.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Object_initializer

2023-04-02 17:21 UTC, tooooo1 commented on src/components/SidoDustDetail.tsx
> +  ];
기존 코드를 이렇게 설계하신 이유가 궁금해요

2023-04-02 17:21 UTC, tooooo1 commented on src/components/SidoDustDetail.tsx
> +              <div>{v[0]}</div>
어떤 값인지 모르겠어요... ㅠ 이전 코드가 훨씬 더 좋은 코드라고 생각해요. 만약 이전 코드에서 더 개선하기 어려우실 것 같다면 이전 코드로 revert 부탁드려요

2023-04-02 17:21 UTC, tooooo1 commented on src/components/SidoDustDetail.tsx
> +const DustStateWrapper = styled.div`
👍

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +};
이부분은 공통타입으로 추출하는 것을 추천드려요

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  const [humidity, setHumidity] = useState();
타입을 명시해주시면 좋을 것 같아요. number라면

```suggestion
  const [temperature, setTemperature] = useState<number | null>(null);
  const [humidity, setHumidity] = useState<number | null>(null);
```

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  const [forecast, setForecast] = useState();
여기두 마찬가지입니다!

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +              ></DustState>
```suggestion
              <DustState
                dustDensity={fineDust}
                kindOfDust="fineDust"
              />
```

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +          <DustState dustDensity={dustState} kindOfDust="avg"></DustState>
```suggestion
          <DustState dustDensity={dustState} kindOfDust="avg" />
```

2023-04-02 17:21 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +              ></DustState>
```suggestion
              />
```

2023-04-03 17:01 UTC, jaekwanAHN commented on src/components/SidoDustDetail.tsx
> +  ];
먼지종류, 먼지 수치를 짝지어서 반복되는 부분을 해결하려고 했어요. 
추후에 새로운 종류의 먼지 혹은 표기할 정보가 추가되더라도 반복문을 통해서 해결할 수 있도록요.
흠.......근데 적절한 방법이었는지는 다시 생각해 봐야겠네요.

2023-04-05 02:13 UTC, tooooo1 requested changes
이제 거의 다 왔네요...! 리뷰할게 거의 안 남았어요 ㅋㅋ
충돌되고 있는 파일이 있어요! 최신화해주신 후에 다시 리뷰 요청 보내주세요!

2023-04-05 02:13 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +          <div>{'기상예보를 준비중 입니다.'}</div>
```suggestion
          <div>기상예보를 준비중 입니다.</div>
```

2023-04-05 02:13 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +        <ForecastImgWrapper></ForecastImgWrapper>
이 tag는 지금 필요없어보이는데 맞을까요?

2023-04-05 02:13 UTC, tooooo1 commented on src/type/index.ts
> +  items: DustDetail[];
👍

2023-04-05 02:13 UTC, tooooo1 commented on src/components/Map/index.tsx
> +import { DEFAULT_LOCATION } from '@/utils/constance';
```suggestion
import { INIT_LOCATION } from '@/utils/constance';
```

올리시기 전에 빌드 확인 해주셨나요?! 파편화되어있네요

2023-04-05 02:30 UTC, tooooo1 approved these changes
고생하셨어요 이만하면 충분히 머지해도 될 것 같네요.
다음 작업에서 이어서 아쉬운 부분 추가적으로 리뷰할게요!

머지하겠습니다!

2023-04-05 02:30 UTC, merged