Refactor: 변수, 함수 이름 변경
tooooo1/dust-rating pull request #31
Opened 2023-04-05 12:48 UTC by jaekwanAHN

## 📌 이슈번호 

- close #28 

## 👩‍💻 요구 사항 
- useQuery를 적용하여 cacheTime, staleTime을 적용하였습니다. 5분의 cacheTime을 두어서 result page 접속 후 다른 페이지로 이동하였다가 다시 돌아와도 cacheTime 이내라면 다시 api 요청이 일어나지 않습니다.

## 🎨 구현 스크린샷 
- result Page와 메인페이지를 왔다갔다 하여도 api 요청이 일어나지 않는 것을 확인하였습니다.
움짤 찍는 방법을 배워오도록 하겠습니다.. :(
## ✅ PR 포인트 
- useQuery가 적절하게 적용되었는지 궁금합니다.
## 질문 
- api문서에 따르면 미세먼지 갱신시간이 15분 단위라서  cacheTime, staleTime을 5분으로 설정하였는데 적절할까요?
- useQuery에서 가져온 data로 화면을 그리지않고 data로 sidoDust라는 state를 갱신시키고 해당 state로 화면을 그리게 되어있는데 data로 직접 화면을 그리는 것이 더 직관적이거나 효율적일까요?

2023-04-05 19:17 UTC, tooooo1 requested changes

2023-04-05 19:17 UTC, tooooo1 commented on src/hooks/useFetchDustInfo.ts
> +  return { dustInfo, fetchData };
둘의 결과 값이 어떤 점이 다른가요?

2023-04-06 15:02 UTC, jaekwanAHN commented on src/hooks/useFetchDustInfo.ts
> +  return { dustInfo, fetchData };
fetchData도 네이밍을 변경해야 했는데 내용이 빠져있었네요.
useQuery에서 data를 가져오는데 이때 data와 네이밍이 겹쳤어요.
const {data: 다른이름} = useQuery() 와 같이 사용할 수 도 있었지만 추후에 다른 fetch 기능이 추가된다면 useFetch함수에서 어떤 데이터를 return 하는지 좀 더 명확하게 표기하면 좋겠다 라고 생각해서 네이밍을 변경했어요.

2023-04-09 05:24 UTC, tooooo1 requested changes
PR 단위가 작아져서 리뷰하기 훨씬 수월해졌네요

## 답변
api문서에 따르면 미세먼지 갱신시간이 15분 단위라서 cacheTime, staleTime을 5분으로 설정하였는데 적절할까요?
- 괜찮을것같아요~ 갱신에 엄청 민감한 데이터는 아니라서용

useQuery에서 가져온 data로 화면을 그리지않고 data로 sidoDust라는 state를 갱신시키고 해당 state로 화면을 그리게 되어있는데 data로 직접 화면을 그리는 것이 더 직관적이거나 효율적일까요?
- 오 이거 너무너무 궁금했는데.. 아래에 리뷰로 달았습니다. 지금은 매우매우 비효율적이라고 생각해요! 기존 로직이 그렇게 짜여있어서 진행하셨다면 바로 바꿔주시죠!ㅋㅋ 리액트 쿼리를 사용하면서 기존로직을 그대로 가져가는건 의미가 없다고 생각해요!

2023-04-09 05:24 UTC, tooooo1 commented on src/hooks/useFetchDustInfo.ts
> +      console.log(err);
```suggestion
      console.error(err);
```

console에서 log보다 error을 쓰면 더 좋을 것 같아요. 아니면 console을 굳이 안 넣어도 되기도하구요!

2023-04-09 05:24 UTC, tooooo1 commented on src/pages/Result.tsx
> +    if (data) setSidoDust(data);
굳이 `setState`에 다시 `data`를 넣고 그 `data`를 뿌려줘야하나요? 바로`data`를 사용하면 훨씬 간편할 것 같아요~ 아니면 혹시 불필요한 연산을 한번 더 진행하신 이유가 따로 있으신가요?

2023-04-10 08:04 UTC, dmswl98 approved these changes
수고하셨습니당

2023-04-10 08:04 UTC, dmswl98 commented on src/hooks/useFetchDustInfo.ts
> +      console.log(err);
이 부분 src/api/airQuality.ts 파일로 분리해두었어요!

2023-04-10 08:04 UTC, dmswl98 commented on src/pages/Result.tsx
> +    if (data) setSidoDust(data);
나중에 바뀌지 않는 값인 것 같아 data를 상태로 관리하지 않아도 될 것 같아요!!!

2023-04-12 06:59 UTC, jaekwanAHN commented on src/hooks/useFetchDustInfo.ts
> +      console.log(err);
return하는 내용이 조금 다른거같아요.
기존의 useFetchDustInfo는 SidorDust 타입의 배열을 리턴해요. 그래서  items[], numOfRows, totalCount, pageNo를 리턴하는데 items에 ```dataTime: string;
  stationName: string;
  pm10Value: string;
  pm25Value: string;
  pm10Grade: string;
  pm25Grade: string;
  sidoName?: string;```
의 내용이 있거든요.
airQuilty.ts는 cityName, pm10Value, pm25Value 만 반환하는거 같은데 맞을까요 ?!

2023-04-12 07:02 UTC, dmswl98 commented on src/hooks/useFetchDustInfo.ts
> +      console.log(err);
그럼 airQuality.ts 파일 내에 모든 데이터를 반환하는 함수를 추가로 생성해도 좋을 것 같아요!

2023-04-12 07:19 UTC, tooooo1 requested changes
굿굿 점점 좋아지네요!

2023-04-12 07:19 UTC, tooooo1 commented on src/pages/Result.tsx
> +      )}
이거 기존 코드대로 하고 위에서 early return을 하면 더 좋을 것 같아요.

return문 밖에서

```tsx
if(isLoading) {
  return <Time>Loading...</Time>;
}
```

이런식으로용

2023-04-12 07:19 UTC, tooooo1 commented on src/pages/Result.tsx
> +            ? 'Loading...'
요기도 위 리뷰랑 동일합니다! 기존 코드대로 하고 early return을 활용해볼까요

2023-04-12 07:19 UTC, tooooo1 commented on src/hooks/useFetchDustInfo.ts
> +        cityGroup.map((v) =>
`v`대신 더 명확한 이름을 쓸까요?

2023-04-12 08:17 UTC, tooooo1 approved these changes

2023-04-12 08:17 UTC, merged