fix: air quality API의 NaN 반환값 없애기
tooooo1/dust-rating pull request #37
Opened 2023-04-12 10:35 UTC by dmswl98

## 📌 이슈번호 

- close #36

## 👩‍💻 요구 사항 
- [x] air quality API [유효한 값 반환하도록 수정](https://github.com/tooooo1/dust-rating/commit/52b00d2c7e6e9c962bc8eb56a68f2eb5fd232eda)
- [x] [마커 중복 생성 해결](https://github.com/tooooo1/dust-rating/commit/8877e5306cafd0b08c3605d963bd03bf330b1d45)

## 🎨 구현 스크린샷 
![image](https://user-images.githubusercontent.com/76807107/231429836-4ee77ee5-a387-4ba3-80d9-5ef04dc6470b.png)

## ✅ PR 포인트 
- 제 생각에 가장 최신의 수치 데이터를 보여주기 위해서 마커는 항상 삭제된 다음에 새로운 마커로 대체되어야 한다고 생각했어요. 그런데 마커가 중복 생성되는 문제가 있었고 이 문제를 이전 pr에서 해결했다고 생각했는데 지도가 확대될 때 마커가 보이지 않는 문제가 있었어요. 
- 커스텀오버레이로 마커를 생성하고 위치시키는 로직을 분리하지 않고 하나로 합쳐서 그 문제를 해결할 수 있었어요.
- air quality API가 유효하지 않은 값을 반환하는 경우가 있었는데, 이는 각 지역의 수치 배열을 순회하면서 해당 수치값의 flag 값을 확인해 유효한 값만 반환하도록 수정했어요.

## 질문 
.

2023-04-12 10:59 UTC, tooooo1 requested changes
PR단위가 작아서 리뷰하기 수월하군요

2023-04-12 10:59 UTC, tooooo1 commented on src/api/airQuality.ts
> +    );
혹시 알고리즘 푸시고 바로 이 로직 짜셨나요?
알고리즘 느낌이 확 나네용~! 동료 개발자분들을 위해 리팩터링을 해주세요~!

2023-04-14 13:29 UTC, dmswl98 commented on src/api/airQuality.ts
> +        }
1. for...of는 유효한 값을 찾은 다음 바로 순회를 멈추기 위해 사용했어요.
2. pm10Flag나 pm25Flag, 즉 flag 값이 null일 때 유효한 값이고 '통신 장애'일 때 유효하지 않은 값이에요. '통신 장애'라는 문자열 값을 비교하기 보다 null 값을 조건문에 사용하면 좋다고 생각했어요.

2023-04-14 13:53 UTC, tooooo1 approved these changes
고생했어요

2023-04-14 13:54 UTC, merged