Feat: 미세먼지 예보 추가
tooooo1/dust-rating pull request #45
Opened 2023-04-16 03:55 UTC by jaekwanAHN

## 📌 이슈번호 

- close #44 

## 👩‍💻 요구 사항 
LocalDetail Page에 기상 예보 정보가 추가되었습니다. 
오늘 날짜를 기준으로 미세먼지와 관련된 기상예보, 기상사진을 가져옵니다.

## 🎨 구현 스크린샷 
![image](https://user-images.githubusercontent.com/12118892/232265228-0f7b1516-cca5-4b72-b656-341e64483f6e.png)

## ✅ PR 포인트 
1. 기상 정보는 지역과 상관없이 전국적으로 전체적인 예보를 가져옵니다.
2. 기상 사진의 특정 시간대 별로 제공되지만 어느 시간대의 사진을 사용해야하는지, 매일 예외없이 제공되는지 확인하지 못하여서 res의 가장 첫 번째 이미지를 사용하였습니다.
3. cacheTime, staleTime을 적용했습니다.

## 질문 
1. 스타일의 경우 임시적으로 적용하였습니다. 어떤식으로 개선이 되었으면 좋겠는지 의견이 필요합니다. ( 미적 감각이 없어서 어떻게 구성해야 할지 감이안오네요...)
2. 미세먼지 예보의 가독성이 좋다는 생각은 들지 않습니다. 어떤식으로 개선할 수 있을까요?
4. 상단의 미세먼지, 초미세먼지 농도를 나타내주는 부분에 숫자도 함께 표기하는 것이 수치를 인식하는데 도움이 될까요?
![image](https://user-images.githubusercontent.com/12118892/232265348-e3fb7b01-9e3b-4797-9893-6706dda7d8dc.png)

2023-04-16 04:14 UTC, dmswl98 approved these changes
바쁘신데 수고하셨어용

2023-04-16 04:14 UTC, dmswl98 commented on src/hooks/useFetchDustForecast.ts
> +  };
getToday 함수를 훅 밖으로 빼도 좋을 것 같아요!
빼게되면 아래 fetch 함수를 따로 두지 않을 수 있을 것 같아요~

2023-04-16 04:34 UTC, tooooo1 requested changes
스타일의 경우 임시적으로 적용하였습니다. 어떤식으로 개선이 되었으면 좋겠는지 의견이 필요합니다. ( 미적 감각이 없어서 어떻게 구성해야 할지 감이안오네요...)

## 답변
- 일단 지금 배치는 좋다고 생각합니다! ㅋㅋ 이정도면 완성도 높이고 스타일에 집중해도 될 것 같아요

미세먼지 예보의 가독성이 좋다는 생각은 들지 않습니다. 어떤식으로 개선할 수 있을까요?
## 답변
- 어느부분이 어떻게 안 좋아보이시나용? 아래 질문에서 이어서 답변드리면될까요

상단의 미세먼지, 초미세먼지 농도를 나타내주는 부분에 숫자도 함께 표기하는 것이 수치를 인식하는데 도움이 될까요?
## 답변
- 몇군데 레퍼런스 찾아보니 수치를 표시하는 것이 대중화가 되어있는 것 같더라구요~ 추가하면 더 좋을 것 같아요. 그리고 날씨도 좋음 안좋음만 보여주는 것 보다는 아이콘도 활용하면 더 좋을 것 같네요!

고생하셨어요!

2023-04-16 04:34 UTC, tooooo1 commented on src/hooks/useFetchDustForecast.ts
> +  };
hook 밖으로 빼도 될 것 같아요

2023-04-16 04:34 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  padding: 10%;
여기 차크라로 스타일이 안 되어있는데 통일하면 더 좋을 것 같아요

2023-04-18 08:42 UTC, tooooo1 approved these changes
고생하셨어요

2023-04-18 08:42 UTC, tooooo1 commented on src/pages/LocalDetail.tsx
> +  const [isLargerThan768] = useMediaQuery('(min-width: 768px)');
오... 신기하네요

2023-04-18 08:42 UTC, merged