refactor: Result 컴포넌트 로직 분리
tooooo1/dust-rating pull request #53
Opened 2023-04-19 12:33 UTC by dmswl98

## 📌 이슈번호 

- close #52 

## 👩‍💻 요구 사항 
- [x] api 데이터 정제를 통해 컴포넌트 내부의 자바스크립트 코드 줄이기
- [x] 컴포넌트 간 불필요한 의존성 없애기

## 🎨 구현 스크린샷 
![image](https://user-images.githubusercontent.com/76807107/233362891-a66e8918-0672-461a-9e77-712ed06a0e46.png)

## ✅ PR 포인트 
- 모호한 네이밍을 명확하게 드러나도록 많은 변경을 시도했어요.
- 기존의 Result 컴포넌트(페이지)명이 모호한 것 같아 Ranking으로 변경했어요.
- useFetchDustInfo 훅이 반환하는 객체 { dustInfo, fetchDustInfo }의 dustInfo는 전혀 사용되지 않고 있어 훅이 있어야 할 필요성을 느끼지 못했어요. 그래서 useFetchDustInfo.ts 파일을 삭제하고 api/airQuality.ts의 api 함수를 활용해 Ranking 컴포넌트를 수정했어요.
- 기존의 시, 도를 의미였던 city 용어를 sido로 통일하고, 그 하위 동, 구, 군을 city로 통일했어요.
- api/airQuality.ts의 getAirQuality -> getSidoAirQualities, getAirQualityByCity -> getCityAirQualities로 이름을 수정했어요.
- Rank 컴포넌트를 SidoRank, SidoDustDetail 컴포넌트를 CityRank로 변경했어요.
- 기존에 DustState 컴포넌트의 prop인 dustDensity가 문자열과 숫자인 문자열을 둘다 받을 수 있다는게 맞지 않는다는 느낌이 들어 prop을 변경했어요, 나중에 제대로 개선할 예정이예요.

## 질문 
1. sido.......? 더 좋은 네이밍이 뭐가 있을까요
2. 더 좋은 네이밍 구해요.
```typescript
interface DustValues {
  pm10Value: string;
  pm25Value: string;
}

interface AirQualityScale extends DustValues {
  pm10Flag: Flag;
  pm25Flag: Flag;
}

interface AirQuality extends DustValues {
  stationName: string;
  pm10Grade: string;
  pm25Grade: string;
  dataTime: string;
}
```

2023-04-20 12:22 UTC, tooooo1 requested changes
네이밍이 더 구체화된 것 같아요~ 훨씬 좋아진 PR이네요. 오늘은 시간이 부족해서 코멘트를 많이 못달아드렸는데 이러한 점이 개선되면 더 좋겠어요.

1. 타입스크립트 재사용성
2. 적재적소에 구조분해할당 -> 현재는 전부 사용되는 듯한 느낌
3. 스타일 통일 -> 어떤건 스타일 변수로, 어떤건 인라인으로 되어있음

2023-04-20 12:22 UTC, tooooo1 commented on src/api/airQuality.ts
> +  pm25Value: string;
타입을 더 재활용하는 방법은 어떤 방법이 있을까요? 재활용하면 좋을 것 같아요

2023-04-20 12:22 UTC, tooooo1 commented on src/components/Ranking/CityRank.tsx
> +        cityAirQualities?.map((city, idx) => (
`cityAirQualities`가 보장이 안 되고 있네요

2023-04-20 12:22 UTC, tooooo1 commented on src/components/Ranking/SidoRank.tsx
> +const SidoRank = ({
👍

2023-04-20 12:22 UTC, tooooo1 commented on src/pages/Ranking.tsx
> +type SortKey = '미세먼지' | '초미세먼지';
`'미세먼지' | '초미세먼지'`는 이미 정의된 것이 있는 것으로 알고 있어요.

2023-04-20 15:23 UTC, jaekwanAHN reviewed
고생하셨습니다.

네이밍은 저도 고민해볼게요.

먼지 종류 상수 관련해서 지금은 ```export const FINE_DUST = '미세먼지';``` 와 같이 한글로 사용될 값들만 상수로 지정했는데 'ultraFineDust, FineDust, avg' 도 2번 이상씩 사용되는거 같더라구요. 해당 값들도 상수화를 하는게 좋을까요?

2023-04-20 15:23 UTC, jaekwanAHN commented on src/components/Ranking/CityRank.tsx
> +        cityAirQualities.map((city, idx) => (
어떤 index 인지 조금 더 구체적인 네이밍으로 바꿀 수 있을거같아요.

2023-04-21 08:34 UTC, dmswl98 commented on src/components/Ranking/CityRank.tsx
> +        cityAirQualities.map((city, idx) => (
@jaekwanAHN 추천 좀....

2023-04-21 08:34 UTC, dmswl98 commented on src/pages/Ranking.tsx
> +  }, [selectedSortKey]);
해볼게요오......!

2023-04-21 10:31 UTC, tooooo1 requested changes

2023-04-21 10:31 UTC, tooooo1 commented on src/api/airQuality.ts
> +interface AirQuality extends DustValues {
이 타입 `src/type/index.ts`에 있지않나요?

2023-04-21 10:31 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +        kindOfDust === 'avg' ? `` : `${fineDust}㎍/㎥`
avg면 `<Box></Box>`가 나오겠네요? 음

2023-04-21 10:31 UTC, tooooo1 commented on src/api/airQuality.ts
> +    );
return type은 무엇인가요?

2023-04-21 11:12 UTC, jaekwanAHN commented on src/components/Ranking/CityRank.tsx
> +        cityAirQualities.map((city, idx) => (
cityAirQualityIdx? 어렵네요 .. 하하 ..

2023-04-21 11:29 UTC, dmswl98 commented on src/components/Dust/DustState.tsx
> +        kindOfDust === 'avg' ? `` : `${fineDust}㎍/㎥`
이 컴포넌트는 아직 리팩토링 진행하지 않았고, Ranking 페이지 리팩토링으로 인해 오류만 없애는 정도로만 고쳤서요.

2023-04-21 11:33 UTC, dmswl98 commented on src/api/airQuality.ts
> +interface AirQuality extends DustValues {
없어요!

2023-04-21 13:02 UTC, tooooo1 approved these changes

2023-04-21 13:02 UTC, merged