refactor: Ranking 페이지 chakra-ui 적용하기
tooooo1/dust-rating pull request #56
Opened 2023-04-21 17:31 UTC by dmswl98

## 📌 이슈번호 

- close #54 

## 👩‍💻 요구 사항 
- [x] Ranking 페이지에 chakra-ui 적용하기

## 🎨 구현 스크린샷 
![image](https://user-images.githubusercontent.com/76807107/233698986-041b4928-a433-4548-a982-6b95a9b69c0c.png)

![image](https://user-images.githubusercontent.com/76807107/233698915-45835f74-9756-487f-a862-015e1f0e9279.png)

## ✅ PR 포인트 

## 질문

2023-04-21 18:51 UTC, jaekwanAHN reviewed
고생하셨습니다!

main 태그는 차크라에서 지원하는게 없는거 같군요😢

2023-04-21 18:51 UTC, jaekwanAHN commented on src/styles/globalStyle.css
> +  /* height: 100vh; */
주석으로 처리하신 이유가 있을까요?

2023-04-21 18:51 UTC, jaekwanAHN commented on src/components/Logo.tsx
Img 태그도 chakra의 Image로 대체할 수 있을까요?

2023-04-22 02:12 UTC, tooooo1 requested changes

2023-04-22 02:12 UTC, tooooo1 commented on src/components/Dust/DustState.tsx
> +        <div>{DUST_RATE[discriminateDust()]}</div>
```suggestion
        <Box>{DUST_ICON[discriminateDust()]}</Box>
        <Box>{DUST_RATE[discriminateDust()]}</Box>
```

2023-04-22 06:38 UTC, dmswl98 commented on src/styles/globalStyle.css
> +  /* height: 100vh; */
앗!

2023-04-22 06:38 UTC, dmswl98 commented on src/components/Logo.tsx
오호 해볼게요.

2023-04-22 06:48 UTC, dmswl98 commented on src/components/Dust/DustState.tsx
> +        <div>{DUST_RATE[discriminateDust()]}</div>
DustState 파일은 아직 손대지 않았서요. 바로 다음 pr에 개선할 예정.

2023-04-22 09:09 UTC, tooooo1 approved these changes

2023-04-22 09:09 UTC, merged