progress 바 수치 변경
tooooo1/dust-rating pull request #75
Opened 2023-04-29 14:59 UTC by jaekwanAHN

## 📌 이슈번호 

- close #74 

## 👩‍💻 요구 사항 
- progress 바의 수치를 변경하여 막대가 더 눈에 잘 띄게 합니다
## 🎨 구현 스크린샷 
![image](https://user-images.githubusercontent.com/12118892/235309344-893d7e94-e07f-43e3-a265-942c2c27ee35.png)

## ✅ PR 포인트 
- 최대치가 100%가 넘어가지 않도록 했습니다.
## 질문 
- 無

2023-04-29 15:50 UTC, dmswl98 reviewed
굿굿!

2023-04-29 15:50 UTC, dmswl98 commented on src/components/ProgressBar.tsx
> +      </DustWrapperFlex>
1. children으로 굳이 사용하지 않아도 될 것 같네요. prop으로 label을 받으면 좋을 것 같아요.
2. 그리고 챠크라로 스타일링 하면 좋을 것 같아요!!!

2023-04-29 15:50 UTC, dmswl98 commented on src/components/ProgressBar.tsx
> +  const percent = +state * (1 / 100) * 100;
state값은 number 타입이라 + 연산자를 사용하지 않아도 될 것 같아요!

2023-04-29 21:53 UTC, tooooo1 requested changes
모든 조건문이 `isLargerThan768` 기준이네요

같은 조건임에도 불구하고 코드를 볼 때마다 굳이 한번 더 생각해야 해서 어지러웠어요

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +        margin={isLargerThan768 ? ' 0 30px' : '0 0.5rem'}
```suggestion
        margin={isLargerThan768 ? '0 30px' : '0 0.5rem'}
```

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
>  // @ts-ignore
```suggestion
```

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +          display="flex"
```suggestion
```

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +        display="flex"
```suggestion
```

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +        margin={isLargerThan768 ? ' 0 30px' : '0 0.5rem'}
어느건 `px`고 어느건 `rem`이군요. 기준이 어떤건가요?

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +          marginLeft={isLargerThan768 ? '20px' : '2vw'}
이것도 기준이 궁금해요

2023-04-29 21:53 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +  const [isLargerThan768] = useMediaQuery('min-width: 768px');
```suggestion
  const [isLargerThan768] = useMediaQuery('(min-width: 768px)');
```

공식문서랑 다르네요 https://chakra-ui.com/docs/hooks/use-media-query

2023-04-29 21:54 UTC, tooooo1 requested changes

2023-04-29 21:54 UTC, tooooo1 commented on src/components/ProgressBar.tsx
> +        <div>{kindOfDust}</div>
```suggestion
        <Box>{kindOfDust}</Box>
```

2023-04-30 02:45 UTC, dmswl98 reviewed
👍

2023-04-30 02:45 UTC, dmswl98 commented on src/components/ProgressBar.tsx
> +      >
```suggestion
  return (
    <DustProgressWrapper id={id}>
      <Flex
        justifyContent="space-between"
        alignItems="center"
        width="30%"
        margin={isLargerThan768 ? '0 30px' : '0 0.5rem'}
        fontSize={isLargerThan768 ? '3vw' : '18px'}
        fontWeight="500"
      >
```
보기 좋게 순서 변경해주시면 좋을 것 같고, 단위는 rem으로 통일하는 건 어때요?

2023-04-30 02:45 UTC, dmswl98 commented on src/components/ProgressBar.tsx
> +const ProgressBar = ({ kindOfDust, id, state }: ProgressBarProps) => {
id prop이 꼭 필요한 건가요??

2023-05-01 10:29 UTC, jaekwanAHN commented on src/components/ProgressBar.tsx
> +const ProgressBar = ({ kindOfDust, id, state }: ProgressBarProps) => {
반복문을 통해서 jsx를 작성할 때 key props가 필요한거랑 같다고 생각했어요.
ProgressBar가 같은 레벨에서 동일하게 2번 쓰여서 서로 다른 key를 가져야 하지 않나? 라고 생각을 했는데 상관없을까요?

2023-05-01 10:36 UTC, tooooo1 approved these changes

2023-05-01 10:36 UTC, merged