fix: 대기질 예보 API 데이터 누락 예외 처리
tooooo1/dust-rating pull request #77
Opened 2023-04-30 19:23 UTC by dmswl98

## 📌 이슈번호 

- close #76 

## 👩‍💻 요구 사항 
- [x] 컴포넌트 분리

## 🎨 구현 스크린샷 
[문제 상황]

https://user-images.githubusercontent.com/76807107/235372375-01cdf421-0041-41f8-a3b4-fe67e7fbafe7.mp4

[해결]

https://user-images.githubusercontent.com/76807107/235372166-aecaf086-e295-49e7-86bd-6e41338f0784.mp4

## ✅ PR 포인트 
![image](https://user-images.githubusercontent.com/76807107/235372188-67fd6d0b-42d3-4dcf-a7cf-19a32c8046b3.png)
DustForcast API로부터 데이터를 받아올 수 있는 시간이 다음과 같아 특정 시간에 데이터가 누락되는 이슈가 있었어요.
예보 페이지(dust-forcast)에서 DustForcast API 데이터를 가져오도록 작성했던 터라 데이터가 누락될 때 해당 페이지의 모든 컨텐츠가 렌더링이 되지 않는 문제도 있었어요.
그래서 컴포넌트를 분리하고 데이터가 없을 때는 alert 컴포넌트를 대신 보이도록 작성해 해결했어요.

## 질문

2023-04-30 19:26 UTC, dmswl98 commented on src/components/DustForcast/DustChart.tsx
> +    labels: dustHistory.map((dust) => dust.hour),
```suggestion
    labels: dustHistories.map((history) => history.hour),
```
가 나으려나...?

2023-04-30 19:48 UTC, tooooo1 requested changes
중복된 타입을 관리하는 것은 매우 좋다고 생각합니다.

셀프리뷰 하신 것만 반영하시면 될 것 같아요-!

2023-04-30 19:48 UTC, tooooo1 commented on src/components/DustForcast/DustChart.tsx
> +    labels: dustHistory.map((dust) => dust.hour),
👍

2023-04-30 19:48 UTC, tooooo1 commented on src/components/Ranking/SidoRank.tsx
> +interface SidoRankProps extends DustFigures {
👍

2023-05-01 02:41 UTC, jaekwanAHN reviewed
고생하셨어요.
타입 관리 어려운거 공감합니다..

2023-05-01 02:41 UTC, jaekwanAHN commented on src/components/DustForcast/DustChart.tsx
> +    labels: dustHistory.map((dust) => dust.hour),
👍

2023-05-01 02:41 UTC, jaekwanAHN commented on src/components/DustForcast/DustChart.tsx
> +      refetchOnWindowFocus: false,
refetchOnWindowFocus를 끄신 이유가 있나용?

2023-05-01 03:09 UTC, dmswl98 commented on src/components/DustForcast/DustChart.tsx
> +      refetchOnWindowFocus: false,
오 데이터 채워지는 시간은 1시간마다라 화면이 포커스될 때마다 굳이 fetch하지 않아도 된다고 생각했어용...

2023-05-01 05:57 UTC, tooooo1 approved these changes

2023-05-01 05:57 UTC, merged