feat: 특정 지역의 미세먼지 농도에 따른 Ranking 페이지 배경색 적용
tooooo1/dust-rating pull request #96
Opened 2023-05-08 14:43 UTC by dmswl98

## 📌 이슈번호 

- close #95 

## 👩‍💻 요구 사항 
- 특정 지역의 미세먼지 농도에 따라 Ranking 페이지의 배경색 적용하기, 애니메이션 구현
- theme 상수를 이용해 기존 DUST_SCALE_COLOR 상수 제거
- 글로벌 스타일 수정 -> 불필요한 flex 스타일 제거
- 폰트 미적용 해결

## 🎨 구현 스크린샷 

https://user-images.githubusercontent.com/76807107/236854051-e00730a9-5bf9-40fa-be2e-d60226c8a553.mp4

https://user-images.githubusercontent.com/76807107/236854089-131baca7-8d6f-46cf-a53d-8a23b625e380.mp4

## ✅ PR 포인트 
- 배경색을 바꾸기 위해 글로벌 스타일을 고쳤습니다.... 다른 페이지 스타일도 수정해야해요.

## 질문 
- 챠크라 theme를 사용하는게 좋은지 아님 기존 상수를 활용하는게 좋은지?

2023-05-09 03:45 UTC, jaekwanAHN reviewed
고생하셨습니다. 
디자인 이뻐요.

폰트 미적용은 어떤게 문제였는지 여쭤봐도 될까요?!

2023-05-09 03:45 UTC, jaekwanAHN commented on src/App.tsx
> +    </ChakraProvider>
기존에 main에 적용 했었었는데 공식문서에는 지금 방법처럼 적용하는 걸로 나와있더라구요.
혹시 기존에 썼던 방법이랑 차이점이 뭔지 알려주실 수 있나요?!

2023-05-09 03:45 UTC, jaekwanAHN commented on src/components/Logo.tsx
> +    </main>
시멘틱하게 사용하려고 하신걸까요?!

2023-05-09 03:45 UTC, jaekwanAHN commented on src/pages/Ranking.tsx
> +`;
👍

2023-05-09 03:45 UTC, jaekwanAHN commented on src/pages/Ranking.tsx
> +        width={{ base: '80%', sm: '80%', md: '60%', lg: '50%', xl: '40%' }}
브레이크 포인트를 3개 잡기로 했던거 같은데, 제일 큰 브레이크 포인트보다 더 커지게 되면 BOX가 너무 커지게 되어서 lg, xl 사이즈도 설정을 하신걸까요?

2023-05-09 06:53 UTC, tooooo1 requested changes
theme를 활용하신거 너무 좋아요! 저는 특이사항 없습니다. 
재관님 리뷰 확인하시면 approve 할게요!

2023-05-09 06:53 UTC, tooooo1 commented on src/styles/theme.ts
> +  },
👍

2023-05-09 06:53 UTC, tooooo1 commented on src/components/Logo.tsx
> +    </main>
차크라에 `main` 태그가 없는걸로 알아요. 그런데 지금 상황에 적절한 시맨틱인지 의문이긴하네요!

2023-05-09 07:27 UTC, dmswl98 commented on src/App.tsx
> +    </ChakraProvider>
main.tsx에서 ChakraProvider 설정이랑 globalStyle.css나 여러 css 파일을 같이 import 했는데, 그럼 css 파일 내용이 안 먹히더라고요! 그래서 그 전에는 ChakraProvider의 theme을 이용해 배경색을 설정했었구요.... 근데 분리하니까 제대로 적용되더라고요!

2023-05-09 07:28 UTC, dmswl98 commented on src/components/Logo.tsx
> +    </main>
흠 이게 저 부분에 챠크라를 쓰면 폰트가 안 먹히더라고요...

2023-05-09 07:50 UTC, dmswl98 commented on src/components/Logo.tsx
> +    </main>
해결 완!!!!!!!!!!

2023-05-09 08:08 UTC, dmswl98 commented on src/pages/Ranking.tsx
> +        width={{ base: '80%', sm: '80%', md: '60%', lg: '50%', xl: '40%' }}
리뷰 반영 완료!

2023-05-10 07:43 UTC, tooooo1 approved these changes

2023-05-10 07:43 UTC, merged