refactor: 중복 코드 함수로 추출
tooooo1/dust-rating pull request #99
Opened 2023-05-09 05:19 UTC by jaekwanAHN

## 📌 이슈번호 

- close #98 

## 👩‍💻 요구 사항 
- 중복되어 있던 코드들을 함수로 추출했습니다.
## 🎨 구현 스크린샷 
- 시,도 단위 / 도시 단위에 상관없이 동일한 마커를 제공합니다.
![image](https://user-images.githubusercontent.com/12118892/237000190-046270aa-11e9-443c-b1fa-c792efd262d6.png)

## ✅ PR 포인트 

## 질문 
- makeMarkerTemplate, setMakerToNull 함수는 재정의 될 필요가 없는 함수들인데 다른 파일로 뺴거나 useCallback을 사용하는 것이 좋을까요?

2023-05-09 06:55 UTC, tooooo1 requested changes
깔끔해졌네요!!!

+ useCallback은 조금만 더 지켜볼까요?! ㅋㅋ

2023-05-09 06:55 UTC, tooooo1 commented on src/components/Map/index.tsx
> +              <span class="divider">&sol;</span>
`&sol;`은 어떤 역할을 해요?

2023-05-09 09:30 UTC, dmswl98 reviewed
굿굿 수고하셨서용

2023-05-10 18:33 UTC, tooooo1 approved these changes

2023-05-10 18:34 UTC, merged